### ISSUE TITLE
Web_UI is black screen

### ISSUE THREAD

**Issue by shawlxin** [ich777/docker-microsoft-edge#2] opened 2024-06-22 09:37 UTC
The Docker installation log is shown in the picture, and the web interface is shown in the picture. Did I install it correctly？
![Snipaste_2024-06-22_17-32-31](https://github.com/ich777/docker-microsoft-edge/assets/162570924/a029b3bf-fbfe-45fb-b06a-4eaf8cec9f32)
![Snipaste_2024-06-22_17-33-12](https://github.com/ich777/docker-microsoft-edge/assets/162570924/572f0edb-1ff1-4327-b311-fb19bcf91fd8)

**Comment by ich777** [comment] 2024-06-22 10:04
Thank you for the report, I will look into that and report back, give me a few hours please.

**Comment by ich777** [comment] 2024-06-22 12:37
@shawlxin please update the container itself and try again, the issue is now fixed!
If you are using Unraid then click the `force update` button on the Docker page.

Please close the issue if it's solved for you.

**Closed as completed** 2024-06-24 09:01 UTC
