### ISSUE TITLE
/start-server.sh: line 107 issue

### ISSUE THREAD

**Issue by brdctrai** [ich777/docker-microsoft-edge#1] opened 2023-04-14 10:23 UTC
---Starting Microsoft Edge---
/opt/scripts/start-server.sh: line 107:    92 Trace/breakpoint trap   (core dumped) ${DATA_DIR}/bin/microsoft-edge --user-data-dir=${DATA_DIR}/profile --disable-accelerated-video --disable-gpu --dbus-stub --no-sandbox --test-type ${EXTRA_PARAMETERS} 2> /dev/null

![image](https://user-images.githubusercontent.com/117452908/232019290-0f2e4d62-3f60-43ec-a929-dc3bbe49ca51.png)

**Comment by ich777** [comment] 2023-04-14 10:50
@brdctrai do you use the container on Unraid? If yes on what Unraid version are you? Is this a fresh installation or was it working before?

Edit: Tried it now with a fresh install and I can't reproduce this on my system:
![grafik](https://user-images.githubusercontent.com/28066518/232025354-9a1547c3-99cd-4324-890b-fc48a85ee33b.png)

**Comment by ich777** [comment] 2023-04-14 10:53
Oh sorry, saw that you are on Ubuntu, what version are you using? Please make sure that you run a up-to-date version.

**Comment by brdctrai** [comment] 2023-04-14 11:20
root@ubuntu-jd:~#  lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by brdctrai** [comment] 2023-04-14 11:22
![image](https://user-images.githubusercontent.com/117452908/232030901-06a7b357-8ef1-4b75-a0f7-f0e8cb546548.png)

**Comment by brdctrai** [comment] 2023-04-14 11:29
root@ubuntu-jd:~# docker images
REPOSITORY                                         TAG       IMAGE ID       CREATED         SIZE
ich777/microsoft-edge                              latest    c864d3631a6f   2 days ago      583MB

**Comment by brdctrai** [comment] 2023-04-14 11:40
Can this container support unbuntu debian?

**Comment by brdctrai** [comment] 2023-04-14 11:40
Can this container support ubuntu debian?

**Comment by ich777** [comment] 2023-04-14 11:44
> Can this container support ubuntu debian?

It sure can since it's based on Debian Bullseye.
You have to upgrade to something more recent since your distribution is somewhat out of date and that's what's most certainly causes the issue.

**Comment by brdctrai** [comment] 2023-04-14 11:44
Can this container support these systems such as ubuntu、debian and Synology these systems? Only for Unraid?

**Comment by ich777** [comment] 2023-04-14 11:45
> Can this container support these systems such as ubuntu、debian and Synology these systems? Only for Unraid?

Yes it can, but as said above, your distribution is out of date.

**Comment by brdctrai** [comment] 2023-04-14 11:46
ubuntu 22?

**Comment by ich777** [comment] 2023-04-14 11:47
> ubuntu 22?

Yes, that should work.

**Comment by brdctrai** [comment] 2023-04-14 11:50
Can this container support these systems such as ARM、ARM64?

**Comment by ich777** [comment] 2023-04-14 11:52
> Can this container support these systems such as ARM、ARM64?

No.

**Comment by ich777** [comment] 2023-04-15 06:06
@brdctrai have you yet tried it on some more recent? I have now tried running it on my Debian Bullseye installation and have no issues running the container.

**Comment by ich777** [comment] 2023-04-18 06:10
Closing due to no further response.

@brdctrai please feel free to open the issue again or create a new issue if you have further issues with the container.

**Closed as completed by ich777** 2023-04-18 06:10 UTC
